services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      sh -c '
      ( (sleep 10; gradle compileKotlin --continuous --parallel --build-cache --configuration-cache --no-daemon -Dorg.gradle.vfs.verbose=true) & ) &&
       gradle bootRun --no-daemon --no-watch-fs'
    ports:
      - 8080:8080
    volumes:
      - ./src/main:/app/src/main
      - gradlecache:/home/gradle/.gradle
    restart: always
volumes:
  gradlecache:
    external: true
      